[package]
name = "node-manager"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = "0.3"
message = { path = "../../message" }
network = { path = "../../network" }
p2p = { path = "../../p2p" }
rpc-client = { path = "../../rpc/client" }