[package]
name = "primitives"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com>"]
edition = "2018"

[dependencies]
heapsize = "0.4"
byteorder = "1.0"
uint = "0.9"
bitcrypto = { path = "../crypto" }
