[package]
name = "serialization"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com>"]
edition = "2018"

[dependencies]
bit-vec = "0.6"
byteorder = "1.0"
hammersbald = { path = "../hammersbald" }
primitives = { path = "../primitives" }
bitcrypto = { path = "../crypto" }
