[package]
name = "network"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
chain = { path = "../chain" }
primitives = { path = "../primitives" }
bitcrypto = { path = "../crypto" }
