[package]
name = "bitcrypto"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com>"]
edition = "2018"

[dependencies]
bitcoin_hashes = { version = "0.7.6", features = ["std", "serde"] }
heapsize = "0.4"
